"%dev":
  quarkus:
    http:
      port: 10001
    datasource:
      db-kind: postgresql
      username: open-erp
      password: open-erp
      jdbc:
        url: jdbc:postgresql://localhost:5432/open-erp
    hibernate-orm:
      schema-management:
        create-schemas: true
        strategy: update
    redis:
      hosts: redis://localhost:6379
    swagger-ui:
      always-include: true

mp:
  jwt:
    verify:
      publickey:
        location: publicKey.pem
      issuer: open-erp-auth

smallrye:
  jwt:
    sign:
      key:
        location: privateKey.pem
