apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway
  namespace: open-erp
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/part-of: open-erp
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.staging.open-erp.local
      secretName: open-erp-tls
  rules:
    - host: api.staging.open-erp.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 80
