apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: open-erp
resources:
  - namespace.yaml
  - configmap-app.yaml
  - secret-app.template.yaml
  - deployment-api-gateway.yaml
  - service-api-gateway.yaml
  - ingress-api-gateway.yaml
  - network-policy.yaml
