apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openerp-staging

resources:
  - ../../base

namePrefix: staging-

patches:
  - target:
      kind: Ingress
      name: openerp-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: staging.openerp.vn
