apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-erp-redis
  namespace: open-erp
  labels:
    app: open-erp-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-erp-redis
  template:
    metadata:
      labels:
        app: open-erp-redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: open-erp-redis-svc
  namespace: open-erp
spec:
  selector:
    app: open-erp-redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
  type: ClusterIP
