export enum ResponseKey {
  // Identity & User
  USER_ID = 'user_id',
  EMAIL = 'email',
  FULL_NAME = 'full_name',
  PHONE = 'phone',
  AVATAR_URL = 'avatar_url',
  STATUS = 'status',
  ROLE = 'role',
  LANGUAGE = 'language',
  TIMEZONE = 'timezone',

  // Tenant & Workspace
  TENANT_ID = 'tenant_id',
  TENANT_SLUG = 'tenant_slug',
  TENANT_NAME = 'tenant_name',
  PERSONAL_TENANT_ID = 'personal_tenant_id',
  TENANTS = 'tenants',
  IS_DEFAULT = 'is_default',

  // Security, Session & Token
  ACCESS_TOKEN = 'access_token',
  REFRESH_TOKEN = 'refresh_token',
  PRE_AUTH_TOKEN = 'pre_auth_token',
  SESSION_ID = 'session_id',
  EXPIRES_IN = 'expires_in',
  USER = 'user',
  DEVICE = 'device',
  IP_ADDRESS = 'ip_address',
  LAST_ACTIVE_AT = 'last_active_at',
  CREATED_AT = 'created_at',
  IS_CURRENT = 'is_current',

  // 2FA Authentication
  REQUIRES_2FA = 'requires_2fa',
  REQUIRES_TENANT_SELECTION = 'requires_tenant_selection',
  IS_ENABLED = 'is_enabled',
  ENABLED_AT = 'enabled_at',
  BACKUP_CODES_REMAINING = 'backup_codes_remaining',
  SECRET_KEY = 'secret_key',
  OTP_AUTH_URI = 'otp_auth_uri',
  QR_CODE_URI = 'qr_code_uri',
  BACKUP_CODES = 'backup_codes',
  MESSAGE = 'message',

  // Generic & Pagination
  ID = 'id',
  ITEMS = 'items',
  PAGE = 'page',
  SIZE = 'size',
  TOTAL_ITEMS = 'total_items',
  TOTAL_PAGES = 'total_pages',
  KEYWORD = 'keyword',
  RESULT = 'result',
  CODE = 'code',
  NAME = 'name',
  DESCRIPTION = 'description',
  TITLE = 'title',
  ADDRESS = 'address',
  TYPE = 'type',
  DATA = 'data',

  // Platform Tenant
  TENANT_TYPE = 'tenant_type',
  PLAN_TIER = 'plan_tier',
  MAX_USERS = 'max_users',
  ACTIVE_USERS_COUNT = 'active_users_count',
  MAX_STORAGE_MB = 'max_storage_mb',
  USED_STORAGE_MB = 'used_storage_mb',
  TRIAL_ENDS_AT = 'trial_ends_at',
  IS_LOCKED = 'is_locked',
  LOCK_REASON = 'lock_reason',
  LOCKED_AT = 'locked_at',
  ALLOWED_PLUGINS = 'allowed_plugins',

  // Platform User & Admin
  ADMIN_ID = 'admin_id',
  IS_2FA_ENABLED = 'is_2fa_enabled',
  TWO_FACTOR_REQUIRED = 'two_factor_required',
  MUST_CHANGE_PASSWORD = 'must_change_password',
  LAST_LOGIN_AT = 'last_login_at',
  DISABLED_AT = 'disabled_at',
  RESET_TOKEN_SENT = 'reset_token_sent',
  FORCE_PASSWORD_RESET = 'force_password_reset',
  SUPPORT_TICKET = 'support_ticket',
  CONFIRM_PASSWORD = 'confirm_password',
  REASON = 'reason',

  // Impersonation
  IMPERSONATION_TOKEN = 'impersonation_token',
  EXPIRES_IN_SECONDS = 'expires_in_seconds',
  TARGET_TENANT_ID = 'target_tenant_id',
  TARGET_TENANT_NAME = 'target_tenant_name',
  TARGET_USER_ID = 'target_user_id',
  TARGET_USER_EMAIL = 'target_user_email',
  STARTED_AT = 'started_at',

  // Audit Log
  LOG_ID = 'log_id',
  EVENT_ID = 'event_id',
  SCOPE = 'scope',
  ACTOR_USER_ID = 'actor_user_id',
  ACTOR_TYPE = 'actor_type',
  ACTOR_EMAIL = 'actor_email',
  ACTION = 'action',
  RESOURCE_TYPE = 'resource_type',
  RESOURCE_ID = 'resource_id',
  CORRELATION_ID = 'correlation_id',
  DETAILS = 'details',
  BEFORE = 'before',
  AFTER = 'after',
  EXTRA = 'extra',
  ENTRY_HASH = 'entry_hash',
  PREV_HASH = 'prev_hash',
  USER_AGENT = 'user_agent',
  FROM_DATE = 'from_date',
  TO_DATE = 'to_date',

  // IAM
  ROLE_ID = 'role_id',
  ROLE_IDS = 'role_ids',
  PERMISSION_IDS = 'permission_ids',
  PERMISSION_ID = 'permission_id',
  DOMAIN = 'domain',
  RESOURCE = 'resource',
  DESCRIPTION_KEY = 'description_key',
  IS_SYSTEM = 'is_system',
  ASSIGNED_USERS_COUNT = 'assigned_users_count',
  ASSIGNED_ROLES_COUNT = 'assigned_roles_count',
  ASSIGNED_AT = 'assigned_at',
  TOTAL_PERMISSIONS_GRANTED = 'total_permissions_granted',
  UPDATED_COUNT = 'updated_count',
  CREATE_SCOPE = 'create_scope',
  READ_SCOPE = 'read_scope',
  UPDATE_SCOPE = 'update_scope',
  DELETE_SCOPE = 'delete_scope',
  EXPORT_SCOPE = 'export_scope',
  SHARE_SCOPE = 'share_scope',
  POLICIES = 'policies',
  ENTITY_CLASS = 'entity_class',
  TABLE_NAME = 'table_name',
  PLUGIN = 'plugin',
  SUPPORTS_ASSIGNEE = 'supports_assignee',

  // Organization
  BRANCH_ID = 'branch_id',
  BRANCH_CODE = 'branch_code',
  BRANCH_NAME = 'branch_name',
  DEPARTMENT_ID = 'department_id',
  DEPARTMENT_NAME = 'department_name',
  DIRECT_MANAGER_USER_ID = 'direct_manager_user_id',
  MANAGER_USER_ID = 'manager_user_id',
  PARENT_ID = 'parent_id',
  NEW_PARENT_ID = 'new_parent_id',
  CHILDREN = 'children',
  IS_PRIMARY = 'is_primary',
  CAN_MANAGE = 'can_manage',
  JOINED_AT = 'joined_at',
  USER_EMAIL = 'user_email',

  // Sample Record & Export
  AMOUNT = 'amount',
  ASSIGNEE_ID = 'assignee_id',
  CREATED_BY = 'created_by',
  UPDATED_AT = 'updated_at',
  FILE_URL = 'file_url',
  DOWNLOAD_URL = 'download_url',
  TOTAL_RECORDS = 'total_records'
}
