package com.vn9melody.openerp.core.enums;

/**
 * Audit/platform action catalog union of DES-02-API section 2.3 and the coverage
 * matrix in SOL-01 section 3.6. Every value maps to its default audit scope.
 */
public enum PlatformAction {
    TENANT_LOCK(AuditScope.PLATFORM),
    TENANT_UNLOCK(AuditScope.PLATFORM),
    TENANT_QUOTA_UPDATE(AuditScope.PLATFORM),
    USER_GLOBAL_LOCK(AuditScope.PLATFORM),
    USER_GLOBAL_UNLOCK(AuditScope.PLATFORM),
    USER_FORCE_PASSWORD_RESET(AuditScope.PLATFORM),
    USER_BREAK_GLASS_DISABLE_2FA(AuditScope.PLATFORM),
    IMPERSONATION_START(AuditScope.PLATFORM),
    IMPERSONATION_END(AuditScope.PLATFORM),
    IMPERSONATION_TIMEOUT(AuditScope.PLATFORM),
    IAM_ROLE_CREATE(AuditScope.TENANT),
    IAM_ROLE_UPDATE(AuditScope.TENANT),
    IAM_ROLE_DELETE(AuditScope.TENANT),
    IAM_ROLE_PERMISSION_UPDATE(AuditScope.TENANT),
    IAM_ROLE_DATA_POLICY_UPDATE(AuditScope.TENANT),
    IAM_USER_ROLE_ASSIGN(AuditScope.TENANT),
    IAM_USER_ROLE_REMOVE(AuditScope.TENANT),
    ORG_BRANCH_CREATE(AuditScope.TENANT),
    ORG_BRANCH_UPDATE(AuditScope.TENANT),
    ORG_BRANCH_DELETE(AuditScope.TENANT),
    ORG_DEPARTMENT_CREATE(AuditScope.TENANT),
    ORG_DEPARTMENT_UPDATE(AuditScope.TENANT),
    ORG_DEPARTMENT_MOVE(AuditScope.TENANT),
    ORG_DEPARTMENT_DELETE(AuditScope.TENANT),
    ORG_MEMBERSHIP_ASSIGN(AuditScope.TENANT),
    ORG_MEMBERSHIP_UPDATE(AuditScope.TENANT),
    ORG_MEMBERSHIP_REMOVE(AuditScope.TENANT),
    ORG_BRANCH_ASSIGNMENT_CREATE(AuditScope.TENANT),
    ORG_BRANCH_ASSIGNMENT_UPDATE(AuditScope.TENANT),
    ORG_BRANCH_ASSIGNMENT_DELETE(AuditScope.TENANT),
    PLUGIN_ACCESS_DENIED(AuditScope.TENANT),
    PLUGIN_REGISTERED(AuditScope.PLATFORM),
    PLUGIN_VERSION_ADDED(AuditScope.PLATFORM),
    PLUGIN_PUBLISHED(AuditScope.PLATFORM),
    PLUGIN_DEPRECATED(AuditScope.PLATFORM),
    PLUGIN_BLOCKED(AuditScope.PLATFORM),
    PLUGIN_UNBLOCKED(AuditScope.PLATFORM),
    PLUGIN_METADATA_UPDATED(AuditScope.PLATFORM),
    PLUGIN_CATALOG_DELETED(AuditScope.PLATFORM),
    PLUGIN_ENTITLEMENT_GRANTED(AuditScope.TENANT),
    PLUGIN_ENTITLEMENT_REVOKED(AuditScope.TENANT),
    TENANT_PLUGIN_INSTALLED(AuditScope.TENANT),
    TENANT_PLUGIN_UNINSTALLED(AuditScope.TENANT),
    TENANT_PLUGIN_ENABLED(AuditScope.TENANT),
    TENANT_PLUGIN_DISABLED(AuditScope.TENANT),
    TENANT_PLUGIN_UPGRADED(AuditScope.TENANT),
    TENANT_PLUGIN_ROLLED_BACK(AuditScope.TENANT),
    TENANT_PLUGIN_FORCE_UNINSTALLED(AuditScope.TENANT),
    TENANT_PLUGIN_BULK_APPLIED(AuditScope.TENANT),
    PLUGIN_TENANT_REGISTERED(AuditScope.TENANT),
    PLUGIN_TENANT_VERSION_ADDED(AuditScope.TENANT),
    PLUGIN_TENANT_VERSION_PUBLISHED(AuditScope.TENANT),
    PLUGIN_TENANT_VERSION_DEPRECATED(AuditScope.TENANT),
    PLUGIN_TENANT_VERSION_REMOVED(AuditScope.TENANT),
    PLUGIN_TENANT_CATALOG_DELETED(AuditScope.TENANT),
    PLATFORM_ADMIN_BOOTSTRAPPED(AuditScope.PLATFORM),
    PLATFORM_ADMIN_GRANTED(AuditScope.PLATFORM),
    PLATFORM_ADMIN_DISABLED(AuditScope.PLATFORM),
    PLATFORM_ADMIN_ENABLED(AuditScope.PLATFORM),
    PLATFORM_ADMIN_REVOKED(AuditScope.PLATFORM),
    PLATFORM_ADMIN_PASSWORD_RESET_SENT(AuditScope.PLATFORM),
    PLATFORM_ADMIN_PASSWORD_CHANGED(AuditScope.PLATFORM),
    PLATFORM_ADMIN_2FA_DISABLED(AuditScope.PLATFORM);

    private final AuditScope defaultScope;

    PlatformAction(AuditScope defaultScope) {
        this.defaultScope = defaultScope;
    }

    public AuditScope getDefaultScope() {
        return defaultScope;
    }

    public static PlatformAction fromString(String value) {
        return EnumParser.parse(PlatformAction.class, value, null);
    }
}
