apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openerp-prod

resources:
  - ../../base

namePrefix: prod-

patches:
  - target:
      kind: Deployment
      name: openerp-backend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 5
  - target:
      kind: Deployment
      name: openerp-web
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - target:
      kind: Ingress
      name: openerp-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: openerp.9ms.io.vn
