%dev.quarkus.http.port=10000
%dev.quarkus.datasource.db-kind=postgresql
%dev.quarkus.datasource.username=open-erp
%dev.quarkus.datasource.password=open-erp
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/open-erp
quarkus.hibernate-orm.schema-management.create-schemas=true
quarkus.hibernate-orm.schema-management.strategy=update