"%dev":
  quarkus:
    http:
      port: 10000
    datasource:
      db-kind: postgresql
      username: open-erp
      password: open-erp
      jdbc:
        url: jdbc:postgresql://localhost:5432/open-erp
    hibernate-orm:
      schema-management:
        create-schemas: true
        strategy: update
    redis:
      hosts: redis://localhost:6379
    swagger-ui:
      always-include: true

mp:
  jwt:
    verify:
      publickey:
        location: publicKey.pem
      issuer: open-erp-auth
  messaging:
    incoming:
      sample-events-in:
        connector: smallrye-kafka
        topic: sample-events
        value:
          deserializer: io.quarkus.kafka.client.serialization.ObjectMapperDeserializer
    outgoing:
      sample-events-out:
        connector: smallrye-kafka
        topic: sample-events
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
