quarkus:
  http:
    port: 8080
  # quinoa:
  #   ui-dir: ../../open-erp-ui
  #   build-dir: dist/open-erp-ui/browser
  #   package-manager: npm
  #   # In dev mode, Quinoa can proxy to Angular dev server or build on demand
  #   dev-server:
  #     port: 4200
  #     check-timeout: 30000
  liquibase:
    migrate-at-start: true
    default-schema: app
"%dev":
  quarkus:
    quinoa:
      dev-server:
        port: 4200
    hibernate-orm:
      database:
        generation:
          type: update

plugin:
  deploy:
    # Chọn môi trường: DEV | DOCKER | KUBERNETES
    target: DOCKER
  # Thư mục lưu trữ artifact khi upload zip
  storage:
    base-dir: /opt/erp/plugins
  static:
    webroot: /var/www/plugins
  k8s:
    pvc-name: plugins-shared-pvc
