apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: open-erp
type: Opaque
stringData:
  rabbitmq-user: admin
  rabbitmq-password: admin123
  jwt-secret: your-secret-key-change-in-production
