package com.vn9melody.openerp.modules.platform.api;

/**
 * Canonical response codes for the Platform Super Admin APIs (DES-02-API section 6.1).
 * Success identifiers and i18n keys are resolved on the frontend from these codes.
 */
public final class PlatformErrorCode {
    private PlatformErrorCode() {}

    // Tenants
    public static final String PLATFORM_TENANT_LIST_SUCCESS = "PLATFORM_TENANT_LIST_SUCCESS";
    public static final String PLATFORM_TENANT_DETAIL_SUCCESS = "PLATFORM_TENANT_DETAIL_SUCCESS";
    public static final String PLATFORM_TENANT_QUOTA_UPDATED = "PLATFORM_TENANT_QUOTA_UPDATED";
    public static final String PLATFORM_TENANT_LOCK_SUCCESS = "PLATFORM_TENANT_LOCK_SUCCESS";
    public static final String PLATFORM_TENANT_UNLOCK_SUCCESS = "PLATFORM_TENANT_UNLOCK_SUCCESS";
    public static final String PLATFORM_TENANT_NOT_FOUND = "PLATFORM_TENANT_NOT_FOUND";
    public static final String PLATFORM_TENANT_QUOTA_EXCEEDED = "PLATFORM_TENANT_QUOTA_EXCEEDED";
    public static final String PLATFORM_PLUGIN_NOT_ALLOWED = "PLATFORM_PLUGIN_NOT_ALLOWED";
    public static final String PLATFORM_TENANT_IMPERSONATION_ACTIVE = "PLATFORM_TENANT_IMPERSONATION_ACTIVE";
    public static final String PLATFORM_SELF_LOCK_FORBIDDEN = "PLATFORM_SELF_LOCK_FORBIDDEN";
    public static final String PLATFORM_PLUGIN_LIST_SUCCESS = "PLATFORM_PLUGIN_LIST_SUCCESS";
    public static final String TENANT_SUSPENDED = "TENANT_SUSPENDED";

    // Global users
    public static final String PLATFORM_USER_LIST_SUCCESS = "PLATFORM_USER_LIST_SUCCESS";
    public static final String PLATFORM_USER_LOCKED_SUCCESS = "PLATFORM_USER_LOCKED_SUCCESS";
    public static final String PLATFORM_USER_UNLOCKED_SUCCESS = "PLATFORM_USER_UNLOCKED_SUCCESS";
    public static final String PLATFORM_USER_PASSWORD_RESET_FORCED = "PLATFORM_USER_PASSWORD_RESET_FORCED";
    public static final String PLATFORM_USER_2FA_DISABLED_BY_BREAK_GLASS = "PLATFORM_USER_2FA_DISABLED_BY_BREAK_GLASS";
    public static final String PLATFORM_USER_NOT_FOUND = "PLATFORM_USER_NOT_FOUND";
    public static final String PLATFORM_SELF_DISABLE_FORBIDDEN = "PLATFORM_SELF_DISABLE_FORBIDDEN";

    // Impersonation
    public static final String PLATFORM_IMPERSONATION_STARTED = "PLATFORM_IMPERSONATION_STARTED";
    public static final String PLATFORM_IMPERSONATION_ENDED = "PLATFORM_IMPERSONATION_ENDED";
    public static final String PLATFORM_IMPERSONATION_LOG_LIST_SUCCESS = "PLATFORM_IMPERSONATION_LOG_LIST_SUCCESS";
    public static final String PLATFORM_IMPERSONATION_TARGET_NOT_FOUND = "PLATFORM_IMPERSONATION_TARGET_NOT_FOUND";
    public static final String PLATFORM_IMPERSONATION_SESSION_EXPIRED = "PLATFORM_IMPERSONATION_SESSION_EXPIRED";
    public static final String PLATFORM_IMPERSONATION_FORBIDDEN = "PLATFORM_IMPERSONATION_FORBIDDEN";
    public static final String PLATFORM_IMPERSONATION_TENANT_LOCKED = "PLATFORM_IMPERSONATION_TENANT_LOCKED";
    public static final String PLATFORM_IMPERSONATION_ALREADY_ACTIVE = "PLATFORM_IMPERSONATION_ALREADY_ACTIVE";

    // Health
    public static final String PLATFORM_HEALTH_CHECK_SUCCESS = "PLATFORM_HEALTH_CHECK_SUCCESS";

    // Audit
    public static final String PLATFORM_AUDIT_LOG_LIST_SUCCESS = "PLATFORM_AUDIT_LOG_LIST_SUCCESS";
    public static final String PLATFORM_AUDIT_LOG_DETAIL_SUCCESS = "PLATFORM_AUDIT_LOG_DETAIL_SUCCESS";
    public static final String PLATFORM_AUDIT_LOG_NOT_FOUND = "PLATFORM_AUDIT_LOG_NOT_FOUND";
    public static final String PLATFORM_AUDIT_CHAIN_VERIFIED = "PLATFORM_AUDIT_CHAIN_VERIFIED";
    public static final String PLATFORM_AUDIT_CHAIN_TAMPERED = "PLATFORM_AUDIT_CHAIN_TAMPERED";
    public static final String PLATFORM_AUDIT_WRITE_FAILED = "PLATFORM_AUDIT_WRITE_FAILED";

    // Platform admins
    public static final String PLATFORM_ADMIN_LIST_SUCCESS = "PLATFORM_ADMIN_LIST_SUCCESS";
    public static final String PLATFORM_ADMIN_GRANTED = "PLATFORM_ADMIN_GRANTED";
    public static final String PLATFORM_ADMIN_INVITATION_SENT = "PLATFORM_ADMIN_INVITATION_SENT";
    public static final String PLATFORM_ADMIN_DISABLED = "PLATFORM_ADMIN_DISABLED";
    public static final String PLATFORM_ADMIN_ENABLED = "PLATFORM_ADMIN_ENABLED";
    public static final String PLATFORM_ADMIN_REVOKED = "PLATFORM_ADMIN_REVOKED";
    public static final String PLATFORM_ADMIN_PASSWORD_RESET_SENT = "PLATFORM_ADMIN_PASSWORD_RESET_SENT";
    public static final String PLATFORM_ADMIN_2FA_DISABLED = "PLATFORM_ADMIN_2FA_DISABLED";
    public static final String PLATFORM_ADMIN_NOT_FOUND = "PLATFORM_ADMIN_NOT_FOUND";
    public static final String PLATFORM_LAST_ADMIN_PROTECTED = "PLATFORM_LAST_ADMIN_PROTECTED";

    // Access control / confirmation
    public static final String PLATFORM_ACCESS_DENIED = "PLATFORM_ACCESS_DENIED";
    public static final String PLATFORM_CONFIRM_PASSWORD_INVALID = "PLATFORM_CONFIRM_PASSWORD_INVALID";
    public static final String PLATFORM_PASSWORD_CHANGE_REQUIRED = "PLATFORM_PASSWORD_CHANGE_REQUIRED";
    public static final String SUPERADMIN_IMPERSONATION_SECRET_EXPORT_FORBIDDEN =
        "SUPERADMIN_IMPERSONATION_SECRET_EXPORT_FORBIDDEN";
}
